In [327]:
import pandas as pd
import random
import math

In [328]:
iris = pd.read_csv("../dataset/iris.csv")

In [329]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [330]:
print("Row, Column:", iris.shape)

Row, Column: (150, 6)

In [331]:
dataset = iris.values.tolist()

for row in dataset[:5]:
    print(row)

[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa']
[2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa']
[3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa']
[4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa']
[5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa']

In [332]:
#Dataset Split Function

def split_dataset(dataset):

    train_set = []
    val_set = []
    test_set = []
    for sample in dataset:
        R = random.random()
        if R <= 0.70:
            train_set.append(sample)
        elif R <= 0.85:
            val_set.append(sample)
        else:
            test_set.append(sample)

    return train_set, val_set, test_set

train_set, val_set, test_set = split_dataset(dataset)

print("Train set:", len(train_set))
print("Validation set:", len(val_set))
print("Test set:", len(test_set))

Train set: 110
Validation set: 19
Test set: 21

In [333]:
# Euclidean Distance Function

def euclidean_distance(sample1, sample2):

    distance = 0

    # exclude last column (class label)
    for i in range(len(sample1)-1):

        distance += (sample1[i] - sample2[i])**2

    return math.sqrt(distance)

print(euclidean_distance(train_set[0], train_set[1]))

1.1357816691600546

In [334]:
# KNN Classification Function

def knn_classification(train_set, validation_sample, K):

    distances = []

    # calculate distance from validation sample to every training sample
    for training_sample in train_set:

        distance = euclidean_distance(validation_sample, training_sample)

        # store distance + class label
        distances.append((distance, training_sample[-1]))

    # sort by smallest distance
    distances.sort()

    # take K nearest neighbors
    neighbors = distances[:K]

    class_count = {}

    # majority voting
    for neighbor in neighbors:

        label = neighbor[1]

        if label not in class_count:
            class_count[label] = 0

        class_count[label] += 1

    # choose most common class
    predicted_class = max(class_count, key=class_count.get)

    return predicted_class

In [335]:
# Test KNN Function

prediction = knn_classification(train_set,val_set[0],5)

print("Prediction:", prediction)
print("Actual:", val_set[0][-1])

Prediction: Iris-setosa
Actual: Iris-setosa

In [336]:
# Accuracy Function

def calculate_accuracy(train_set, validation_set, K):

    correct = 0

    for sample in validation_set:

        predicted = knn_classification(train_set,sample,K)

        actual = sample[-1]

        if predicted == actual:
            correct += 1

    accuracy = (correct / len(validation_set)) * 100

    return accuracy

In [337]:
# Validation Experiment

K_values = [1,3,5,10,15]

results = []

for K in K_values:

    accuracy = calculate_accuracy(train_set,val_set,K)

    results.append([K, accuracy])

    print("K =", K,"| Accuracy =", round(accuracy,2))

K = 1 | Accuracy = 100.0
K = 3 | Accuracy = 100.0
K = 5 | Accuracy = 89.47
K = 10 | Accuracy = 89.47
K = 15 | Accuracy = 89.47

In [338]:
# Create Results Table

results_df = pd.DataFrame(results,columns=["K","Validation Accuracy"])

results_df

    K  Validation Accuracy
0   1           100.000000
1   3           100.000000
2   5            89.473684
3  10            89.473684
4  15            89.473684

In [339]:
# Find Best K

best_row = max(results,key=lambda x: x[1])

best_K = best_row[0]
best_accuracy = best_row[1]

print("Best K:", best_K)
print("Best Validation Accuracy:",round(best_accuracy,2))

Best K: 1
Best Validation Accuracy: 100.0

In [340]:
# Final Test Accuracy

test_accuracy = calculate_accuracy(train_set,test_set,best_K)

print("Final Test Accuracy:",round(test_accuracy,2))

Final Test Accuracy: 100.0